name: Fail PR
description: Fail PR 
runs:
  using: "composite"
  steps:
    - name: Comment on PR and mark as draft if build fails
      shell: bash
      run: |
        gh pr convert ${{ env.BRANCH_NAME }} --draft
        gh pr comment ${{ env.BRANCH_NAME }} --body "Build failed. Please review the logs and address the issues."
        gh pr edit ${{ env.BRANCH_NAME }} --add-label "BUILD FAILED"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
