
cargo-features = ["edition2024"]


[package]
name = "rav"
version = "0.2.2"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
cpal = "0.15.3"
crossbeam-channel = "0.5.14"
crossterm = "0.28.1"
ratatui = "0.29.0"
rustfft = "6.2.0"
thiserror = "2.0.11"
