name: PR Ready
description: PR Ready
runs:
  using: "composite"
  steps:
    - name: Update PR to ready for review if build succeeds
      shell: bash
      run: |
        gh pr ready ${{ env.BRANCH_NAME }}
        gh pr edit ${{ env.BRANCH_NAME }} --add-label "READY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
