name: PR Ready
description: PR Ready
runs:
  using: "composite"
  steps:
    - name: Derive branch name
      id: vars
      shell: bash
      run: |
        echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Update PR to ready for review if build succeeds
      shell: bash
      run: |
        gh pr ready ${{ env.BRANCH_NAME }}
        gh pr edit ${{ env.BRANCH_NAME }} --remove-label "DRAFT" --add-label "READY"
      env:
        GH_TOKEN: ${{ github.token }}
