//! Turns the bundled themes into Rust consts at build time.
//!
//! So a target can have rav's themes without carrying a TOML parser to read
//! them. The generated consts are plain data - `Ink` is a C-like enum of `u8`
//! payloads - so they land in read-only memory and cost an allocator nothing.
//!
//! The colour-name table is `include!`d from the crate rather than repeated
//! here, because a generator that disagreed with the runtime parser about what
//! `bright-cyan` means would produce a binary whose built-in themes differ from
//! the same file loaded from disk. The rest of the agreement is checked by
//! `the_generated_themes_match_the_parser`.

use std::fmt::Write as _;
use std::path::Path;

include!("src/names.rs");

/// Stops in the analyser ramp, and in a per-stop backdrop.
const STOPS: usize = 16;
/// Levels in the oscilloscope ladder.
const SCOPE_LEVELS: usize = 5;

fn main() {
    let themes = Path::new("themes");
    println!("cargo:rerun-if-changed=themes");
    println!("cargo:rerun-if-changed=src/names.rs");

    // Explicit, not alphabetical. The first entry is the default theme and the
    // rest is the order `t` cycles, so sorting by filename would have quietly
    // made `mono` the default and reshuffled the cycle - which is a curation
    // decision rather than a property of any one file, and belongs here where
    // it can be read.
    //
    // A theme file that is not listed fails the build rather than landing last
    // unnoticed.
    const ORDER: [&str; 4] = ["rav", "winamp", "terminal", "mono"];

    let found: Vec<_> = std::fs::read_dir(themes)
        .expect("themes/ must exist beside this build script")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|e| e == "toml"))
        .collect();
    for path in &found {
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        assert!(
            ORDER.contains(&stem.as_str()),
            "{stem} is not in ORDER; add it where it should sit in the cycle"
        );
    }
    let files: Vec<_> = ORDER
        .iter()
        .map(|name| {
            let path = themes.join(format!("{name}.toml"));
            assert!(path.is_file(), "ORDER names {name}, which is not there");
            path
        })
        .collect();

    // No imports: this is `include!`d into theme.rs, where the names are already
    // in scope, and a `use` here would collide with them.
    let mut out = String::from("// Generated by build.rs from themes/*.toml. Do not edit.\n\n");
    let mut names = Vec::new();

    for path in &files {
        let text = std::fs::read_to_string(path).expect("readable theme");
        let parsed: toml::Value = text.parse().expect("valid TOML");
        let name = parsed["name"].as_str().expect("a theme has a name");
        let ident = name.to_uppercase().replace('-', "_");
        names.push((name.to_string(), ident.clone()));

        let colors = &parsed["colors"];
        let darken = darken_of(parsed.get("darken"));

        writeln!(out, "pub static {ident}: StaticTheme = StaticTheme {{").unwrap();
        writeln!(out, "    name: {name:?},").unwrap();
        writeln!(out, "    bars: {},", ladder(&colors["bars"], STOPS)).unwrap();
        writeln!(out, "    grid: {},", ladder(&colors["grid"], STOPS)).unwrap();
        writeln!(out, "    peak: {},", ink(colors["peak"].as_str().unwrap())).unwrap();
        writeln!(
            out,
            "    scope: {},",
            ladder(&colors["scope"], SCOPE_LEVELS)
        )
        .unwrap();
        writeln!(out, "    darken: {darken},").unwrap();
        writeln!(out, "}};\n").unwrap();
    }

    // First is the default, and the order is the one `t` cycles - which is the
    // order of the files, so a new theme joins the cycle by being added.
    writeln!(
        out,
        "/// Every theme rav ships, in the order `t` cycles them.\n\
         pub static BUILT_IN: [(&str, &StaticTheme); {}] = [",
        names.len()
    )
    .unwrap();
    for (name, ident) in &names {
        writeln!(out, "    ({name:?}, &{ident}),").unwrap();
    }
    writeln!(out, "];").unwrap();

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("built_in.rs");
    std::fs::write(dest, out).expect("writable OUT_DIR");
}

/// A ramp is one colour or a full ladder; one means "this colour all the way
/// up", which is how `mono` is written.
fn ladder(value: &toml::Value, len: usize) -> String {
    let inks: Vec<String> = match value {
        toml::Value::String(one) => vec![ink(one); len],
        toml::Value::Array(many) => {
            assert_eq!(many.len(), len, "a ladder needs 1 or {len} colours");
            many.iter().map(|v| ink(v.as_str().unwrap())).collect()
        }
        other => panic!("a colour is a string or an array, not {other:?}"),
    };
    format!("[{}]", inks.join(", "))
}

/// `#rrggbb`, or one of the sixteen ANSI names.
fn ink(text: &str) -> String {
    let text = text.trim();
    if let Some(hex) = text.strip_prefix('#') {
        assert_eq!(hex.len(), 6, "a hex colour is #rrggbb, not {text:?}");
        let byte = |at: usize| u8::from_str_radix(&hex[at..at + 2], 16).expect("hex digits");
        return format!("Ink::Rgb({}, {}, {})", byte(0), byte(2), byte(4));
    }
    let slot = ANSI_NAMES
        .iter()
        .position(|&n| n == text)
        .unwrap_or_else(|| panic!("{text:?} is not a colour"));
    format!("Ink::Ansi({slot})")
}

/// `darken` is `true` for the default strength, a number for how much
/// brightness to keep, or absent to leave the backdrop alone.
///
/// Three shapes, and reading it as a table with a `floor` key silently gave the
/// `terminal` theme no darkening at all - caught by the test that compares these
/// consts against the runtime parser, which is the whole reason that test exists.
fn darken_of(value: Option<&toml::Value>) -> String {
    /// Matches DEFAULT_DARKEN in the runtime parser.
    const DEFAULT: f32 = 0.25;
    match value {
        None | Some(toml::Value::Boolean(false)) => "None".to_string(),
        Some(toml::Value::Boolean(true)) => format!("Some({DEFAULT}f32)"),
        Some(toml::Value::Float(f)) => format!("Some({}f32)", f.clamp(0.0, 1.0)),
        Some(toml::Value::Integer(i)) => {
            format!("Some({}f32)", (*i as f32).clamp(0.0, 1.0))
        }
        Some(other) => panic!("darken is true or a number, not {other:?}"),
    }
}
