name: Release
description: Create release using release-please

outputs:
  release_uploaded:
    description: "Whether a release was uploaded"
    value: ${{ false }}

runs:
  using: "composite"
  steps:    
    - name: Run Release Please
      id: release
      uses: googleapis/release-please-action@v4
      with:
        config-file: release-please-config.json
        token: ${{ github.token }}

    # - name: DEBUG
    #   shell: bash
    #   run: |
    #     echo ${{ ToJson(steps.release.outputs )}}

    - name: Build New Version
      if: steps.release.outputs.prs_created
      uses: ./.github/jobs/rust/build

    - name: Upload to Github Release
      if: steps.release.outputs.release_created
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TAG_NAME: ${{ steps.release.outputs.tag_name }}
      run: |
        for file in result/bin/*; do
          gh release upload "$TAG_NAME" "$file"
        done
        echo "release_uploaded=true" >> "$GITHUB_OUTPUT"


