name: Release
description: Create release using release-please

outputs:
  release_created:
    description: "Whether a release was created"
    value: ${{ steps.release.outputs.release_created }}

runs:
  using: "composite"
  steps:    
    - name: Run Release Please
      id: release
      uses: googleapis/release-please-action@v4
      with:
        config-file: release-please-config.json
        token: ${{ github.token }}

    - name: Build New Version
      if: steps.release.outputs.prs_created
      uses: ./.github/jobs/rust/build

    - name: Auto-approve Release PR
      if: steps.release.outputs.release_created != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ steps.release.outputs.pr.number }}

      run: |
        gh pr $PR_NUMBER review --approve
        gh pr $PR_NUMBER merge --squash --auto

    - name: Upload to Github Release
      if: steps.release.outputs.release_created
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        echo $TAG_NAME
        exit 1
        for file in result/bin/*; do
          gh release upload "$TAG_NAME" "$file"
        done

