name: Publish Crate
description: Publish Crate 
runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Log in to crates.io
      shell: bash
      run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - name: Publish crate
      shell: bash
      run: cargo publish #--allow-dirty

