name: Publish Crate
description: Publish Crate
inputs:
  cargo_registry_token:
    description: Crates.io token
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Log in to crates.io
      shell: bash
      run: cargo login ${{ inputs.cargo_registry_token }}

    - name: Publish crate
      shell: bash
      run: cargo publish #--allow-dirty
