name: Pull Request

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set branch name
        id: vars
        run: |
          echo "BRANCH_NAME=${{ github.ref }}" | sed 's/refs\/heads\///' >> $GITHUB_ENV

      - name: Log branch name
        shell: bash
        run: |
          echo "Branch Name: ${{ env.BRANCH_NAME }}"

      - name: Run create PR action
        run: ./.github/jobs/pr/create/action.yml

  build:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: ./.github/jobs/build/action.yml

  manage-pr:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ready action
        if: success()
        run: ./.github/jobs/pr/ready/action.yml

      - name: Run fail action if build fails
        if: failure()
        run: ./.github/jobs/pr/fail/action.yml
