name: Pull Request

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: create Draft PR
        uses : ./.github/jobs/pr/create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - uses: actions/checkout@v4 
      - name: Build
        uses: ./.github/jobs/rust/build

  manage-pr:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: actions/checkout@v4 
      - name: Run ready action
        if: success()
        uses: ./.github/jobs/pr/ready
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run fail action if build fails
        if: failure()
        uses: ./.github/jobs/pr/fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
