name: Pull Request

on:
  push:
    branches: [ '**' ]

permissions:
  contents: write
  pull-requests: write

jobs:
  manage-pr:
    name: Manage PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
          # ref: ${{ github.head_ref }}
      - name: create Draft PR
        uses : ./.github/jobs/pr/create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: manage-pr
    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: ${{ github.head_ref }}
      - name: Build
        uses: ./.github/jobs/rust/build

  manage-pr-success:
    name: Manage PR (Success)
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run ready action
        uses: ./.github/jobs/pr/ready
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  manage-pr-failure:
    name: Manage PR (Failure)
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run fail action
        uses: ./.github/jobs/pr/fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
